services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: david
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: mysqldb
    ports:
      - "3306:3306"
    volumes:
      - ./mysqldata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9010:9010"
    command: ./main
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
