services:
  db:
    image: mysql:latest
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - ./mysqldata:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9010:9010"
    command: ./main
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
